/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f5",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c9c6c2",
        "on-primary-container": "#819986",
        "on-background": "#1e1b18",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb77b",
        "surface-container-high": "#efe6e2",
        "on-error-container": "#93000a",
        "primary-container": "#1b3022",
        "inverse-surface": "#34302c",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#6d3a00",
        "background": "#fff8f5",
        "on-secondary-fixed-variant": "#474743",
        "primary": "#061b0e",
        "tertiary-container": "#462300",
        "secondary-fixed": "#e5e2dd",
        "primary-fixed": "#d0e9d4",
        "on-primary-fixed": "#0b2013",
        "surface-variant": "#e9e1dc",
        "on-surface": "#1e1b18",
        "tertiary": "#281200",
        "surface-container-highest": "#e9e1dc",
        "on-secondary-container": "#656461",
        "secondary-container": "#e5e2dd",
        "primary-fixed-dim": "#b4cdb8",
        "on-secondary-fixed": "#1c1c19",
        "inverse-on-surface": "#f8efea",
        "inverse-primary": "#b4cdb8",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#2e1500",
        "surface-container": "#f5ece7",
        "on-surface-variant": "#434843",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#cb8341",
        "on-primary-fixed-variant": "#364c3c",
        "surface-tint": "#4d6453",
        "surface-bright": "#fff8f5",
        "outline": "#737973",
        "surface-dim": "#e1d8d4",
        "tertiary-fixed": "#ffdcc2",
        "outline-variant": "#c3c8c1",
        "surface-container-low": "#fbf2ed",
        "secondary": "#5f5e5b",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "24px",
        "container-max": "1280px",
        "unit": "8px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Lora", "serif"],
        "headline-lg": ["Lora", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Lora", "serif"],
        "headline-xl": ["Lora", "serif"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.03em", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
